# AUTO-GENERATED by scripts/gen_review_cg_testcase.py. Do not edit by hand.

testsuite screenshot_review_cg:
    setup:
        $ _test.screenshot_directory = ""
        $ _test.transition_timeout = 0.05
        $ _test.timeout = 900.0
        $ preferences.text_cps = 0
        $ preferences.afm_enable = True
        $ preferences.afm_time = 0

    testcase review_cg_catalog_generated:
        $ _review_cg_tag = "moment prologue_door_choices"
        run Jump("_review_show_cg")
        advance repeat 12
        pause 0.35
        screenshot "screenshots/review-2026-06-02/cg/prologue/010-prologue_door_choices"

        $ _review_cg_tag = "moment prologue_door_second_chance"
        run Jump("_review_show_cg")
        advance repeat 12
        pause 0.35
        screenshot "screenshots/review-2026-06-02/cg/prologue/020-prologue_door_second_chance"

        $ _review_cg_tag = "moment prologue_formality_menu"
        run Jump("_review_show_cg")
        advance repeat 12
        pause 0.35
        screenshot "screenshots/review-2026-06-02/cg/prologue/030-prologue_formality_menu"

        $ _review_cg_tag = "moment prologue_enter_office_menu"
        run Jump("_review_show_cg")
        advance repeat 12
        pause 0.35
        screenshot "screenshots/review-2026-06-02/cg/prologue/040-prologue_enter_office_menu"

        $ _review_cg_tag = "permit_desk"
        run Jump("_review_show_cg")
        advance repeat 12
        pause 0.35
        screenshot "screenshots/review-2026-06-02/cg/prologue/050-permit_desk"

        $ _review_cg_tag = "moment prologue_before_dance_menu"
        run Jump("_review_show_cg")
        advance repeat 12
        pause 0.35
        screenshot "screenshots/review-2026-06-02/cg/prologue/060-prologue_before_dance_menu"

        $ _review_cg_tag = "moment prologue_refuse_retry_menu"
        run Jump("_review_show_cg")
        advance repeat 12
        pause 0.35
        screenshot "screenshots/review-2026-06-02/cg/prologue/070-prologue_refuse_retry_menu"

        $ _review_cg_tag = "office_dance"
        run Jump("_review_show_cg")
        advance repeat 12
        pause 0.35
        screenshot "screenshots/review-2026-06-02/cg/prologue/080-office_dance"

        $ _review_cg_tag = "moment prologue_grab_menu"
        run Jump("_review_show_cg")
        advance repeat 12
        pause 0.35
        screenshot "screenshots/review-2026-06-02/cg/prologue/090-prologue_grab_menu"

        $ _review_cg_tag = "chair_tension"
        run Jump("_review_show_cg")
        advance repeat 12
        pause 0.35
        screenshot "screenshots/review-2026-06-02/cg/prologue/100-chair_tension"

        $ _review_cg_tag = "canon_proposition"
        run Jump("_review_show_cg")
        advance repeat 12
        pause 0.35
        screenshot "screenshots/review-2026-06-02/cg/prologue/110-canon_proposition"

        $ _review_cg_tag = "corridor_lost"
        run Jump("_review_show_cg")
        advance repeat 12
        pause 0.35
        screenshot "screenshots/review-2026-06-02/cg/prologue/120-corridor_lost"

        $ _review_cg_tag = "canon_pull_close"
        run Jump("_review_show_cg")
        advance repeat 12
        pause 0.35
        screenshot "screenshots/review-2026-06-02/cg/canon/010-canon_pull_close"

        $ _review_cg_tag = "canon_undressing"
        run Jump("_review_show_cg")
        advance repeat 12
        pause 0.35
        screenshot "screenshots/review-2026-06-02/cg/canon/020-canon_undressing"

        $ _review_cg_tag = "canon_embrace"
        run Jump("_review_show_cg")
        advance repeat 12
        pause 0.35
        screenshot "screenshots/review-2026-06-02/cg/canon/030-canon_embrace"

        $ _review_cg_tag = "canon_afterglow"
        run Jump("_review_show_cg")
        advance repeat 12
        pause 0.35
        screenshot "screenshots/review-2026-06-02/cg/canon/040-canon_afterglow"

        $ _review_cg_tag = "canon_signing"
        run Jump("_review_show_cg")
        advance repeat 12
        pause 0.35
        screenshot "screenshots/review-2026-06-02/cg/canon/050-canon_signing"

        $ _review_cg_tag = "canon_three_days"
        run Jump("_review_show_cg")
        advance repeat 12
        pause 0.35
        screenshot "screenshots/review-2026-06-02/cg/canon/060-canon_three_days"

        $ _review_cg_tag = "moment case1_companion_accept_menu"
        run Jump("_review_show_cg")
        advance repeat 12
        pause 0.35
        screenshot "screenshots/review-2026-06-02/cg/case1/010-case1_companion_accept_menu"

        $ _review_cg_tag = "moment case1_first_duty_menu"
        run Jump("_review_show_cg")
        advance repeat 12
        pause 0.35
        screenshot "screenshots/review-2026-06-02/cg/case1/020-case1_first_duty_menu"

        $ _review_cg_tag = "moment case1_briefing_menu"
        run Jump("_review_show_cg")
        advance repeat 12
        pause 0.35
        screenshot "screenshots/review-2026-06-02/cg/case1/030-case1_briefing_menu"

        $ _review_cg_tag = "moment case1_canal_menu"
        run Jump("_review_show_cg")
        advance repeat 12
        pause 0.35
        screenshot "screenshots/review-2026-06-02/cg/case1/040-case1_canal_menu"

        $ _review_cg_tag = "moment case1_kaoru_probe_menu"
        run Jump("_review_show_cg")
        advance repeat 12
        pause 0.35
        screenshot "screenshots/review-2026-06-02/cg/case1/050-case1_kaoru_probe_menu"

        $ _review_cg_tag = "moment case1_registry_menu"
        run Jump("_review_show_cg")
        advance repeat 12
        pause 0.35
        screenshot "screenshots/review-2026-06-02/cg/case1/060-case1_registry_menu"

        $ _review_cg_tag = "moment case1_witness_menu"
        run Jump("_review_show_cg")
        advance repeat 12
        pause 0.35
        screenshot "screenshots/review-2026-06-02/cg/case1/070-case1_witness_menu"

        $ _review_cg_tag = "moment case1_ledger_menu"
        run Jump("_review_show_cg")
        advance repeat 12
        pause 0.35
        screenshot "screenshots/review-2026-06-02/cg/case1/080-case1_ledger_menu"

        $ _review_cg_tag = "moment case1_barge_menu"
        run Jump("_review_show_cg")
        advance repeat 12
        pause 0.35
        screenshot "screenshots/review-2026-06-02/cg/case1/090-case1_barge_menu"

        $ _review_cg_tag = "case1_romance_lantern"
        run Jump("_review_show_cg")
        advance repeat 12
        pause 0.35
        screenshot "screenshots/review-2026-06-02/cg/case1/100-case1_romance_lantern"

        $ _review_cg_tag = "gameover_case1_canal"
        run Jump("_review_show_cg")
        advance repeat 12
        pause 0.35
        screenshot "screenshots/review-2026-06-02/cg/case1/110-gameover_case1_canal"

        $ _review_cg_tag = "moment case2_briefing_menu"
        run Jump("_review_show_cg")
        advance repeat 12
        pause 0.35
        screenshot "screenshots/review-2026-06-02/cg/case2/010-case2_briefing_menu"

        $ _review_cg_tag = "moment case2_alley_menu"
        run Jump("_review_show_cg")
        advance repeat 12
        pause 0.35
        screenshot "screenshots/review-2026-06-02/cg/case2/020-case2_alley_menu"

        $ _review_cg_tag = "moment case2_desk_menu"
        run Jump("_review_show_cg")
        advance repeat 12
        pause 0.35
        screenshot "screenshots/review-2026-06-02/cg/case2/030-case2_desk_menu"

        $ _review_cg_tag = "case2_romance_morning"
        run Jump("_review_show_cg")
        advance repeat 12
        pause 0.35
        screenshot "screenshots/review-2026-06-02/cg/case2/040-case2_romance_morning"

        $ _review_cg_tag = "gameover_case2_exile"
        run Jump("_review_show_cg")
        advance repeat 12
        pause 0.35
        screenshot "screenshots/review-2026-06-02/cg/case2/050-gameover_case2_exile"

        $ _review_cg_tag = "gameover_rain_flee"
        run Jump("_review_show_cg")
        advance repeat 12
        pause 0.35
        screenshot "screenshots/review-2026-06-02/cg/gameover-rain/010-gameover_rain_flee"

        $ _review_cg_tag = "gameover_rain_run"
        run Jump("_review_show_cg")
        advance repeat 12
        pause 0.35
        screenshot "screenshots/review-2026-06-02/cg/gameover-rain/020-gameover_rain_run"

        $ _review_cg_tag = "gameover_rain_alone"
        run Jump("_review_show_cg")
        advance repeat 12
        pause 0.35
        screenshot "screenshots/review-2026-06-02/cg/gameover-rain/030-gameover_rain_alone"

        exit
