#!/usr/bin/env python3
"""Generate game/test_screenshot_review_cg_generated.rpy from REVIEW_CG_CATALOG."""

from __future__ import annotations

import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "game", "test_screenshot_review.rpy")
OUT = os.path.join(ROOT, "game", "test_screenshot_review_cg_generated.rpy")

pattern = re.compile(r'\("([^"]+)",\s*"([^"]+)",\s*"([^"]+)"\)')


def main() -> int:
    text = open(SRC, encoding="utf-8").read()
    entries = []
    in_catalog = False
    for line in text.splitlines():
        if "REVIEW_CG_CATALOG = [" in line:
            in_catalog = True
            continue
        if in_catalog:
            if line.strip() == "]":
                break
            m = pattern.search(line)
            if m:
                entries.append(m.groups())

    lines = [
        "# AUTO-GENERATED by scripts/gen_review_cg_testcase.py — do not edit by hand.",
        "",
        "testsuite screenshot_review_cg:",
        "    setup:",
        '        $ _test.screenshot_directory = ""',
        "        $ _test.transition_timeout = 0.05",
        "        $ _test.timeout = 900.0",
        "        $ preferences.text_cps = 0",
        "        $ preferences.afm_enable = True",
        "        $ preferences.afm_time = 0",
        "",
        "    testcase review_cg_catalog_generated:",
    ]
    for rel_base, tag, _desc in entries:
        path = f"screenshots/review-2026-06-02/{rel_base}"
        lines.append(f'        $ _review_cg_tag = "{tag}"')
        lines.append('        run Jump("_review_show_cg")')
        lines.append("        advance repeat 12")
        lines.append("        pause 0.35")
        lines.append(f'        screenshot "{path}"')
        lines.append("")

    lines.append("        exit")
    lines.append("")

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"Wrote {OUT} ({len(entries)} shots)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
